### ISSUE TITLE
'module' object has no attribute 'get' error

### ISSUE THREAD

**Issue by mshry88** [smartbutnot/flightportal#24]
I got a handfull of errors that I have been able to sort through but one has me stuck. 

First I got an error about the library adafruit_ticks missing. I added that and then I got and error on line 144 saying that .show() has been romoved and to chang it to .root_group = x. That changed seemed to fix that issue. 

Now where I am stuck. It connects to the internet then throws the following error. 

Traceback (most recent call last):
  File "code.py", line 420, in <module>
  File "code.py", line 388, in get_flights
AttributeError: 'module' object has no attribute 'get'

Not sure if those first two isses may be related to to this get error. Any help is appreciated.

**Comment by mshry88** [comment]
Switching to Circuitpython 8.2 from the latest Circuitpython corrected most of this.
